version: '3.9'

services:
  app:
    image: daqiancode/mini-oauth2:0.0.1
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/minioauth2
      - REDIS_URL=redis://redis:6379/0
      - EXTERNAL_DOMAIN=http://localhost:4000
      - ADMIN_API_KEY=123
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    networks:
      - mini-oauth2-network

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minioauth2
    # ports:
    #   - "5432:5432"
    networks:
      - mini-oauth2-network

  redis:
    image: redis:8-alpine
    # ports:
    #   - "6379:6379"
    networks:
      - mini-oauth2-network

networks:
  mini-oauth2-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: