"""roles

Revision ID: 1229c0434b88
Revises: 7c178754748d
Create Date: 2025-06-16 19:15:21.872530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1229c0434b88'
down_revision: Union[str, None] = '7c178754748d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.String(length=200), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
