"""oauth2

Revision ID: b64bff4c45de
Revises: 15659924b381
Create Date: 2025-09-16 10:01:26.070800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64bff4c45de'
down_revision: Union[str, None] = '15659924b381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('allowed_uris', sa.JSON(), nullable=True, comment='allowed uris'))
    op.drop_column('clients', 'allowed_domains')
    op.add_column('users', sa.Column('provider', sa.String(length=30), nullable=True))
    op.drop_column('users', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('users', 'provider')
    op.add_column('clients', sa.Column('allowed_domains', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='allowed domains, separated by comma'))
    op.drop_column('clients', 'allowed_uris')
    # ### end Alembic commands ###
