"""key_len_2k

Revision ID: b6ce5789f55e
Revises: b64bff4c45de
Create Date: 2025-09-16 13:36:59.407629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ce5789f55e'
down_revision: Union[str, None] = 'b64bff4c45de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'jwt_public_key',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_comment='jwt public key with pem format',
               existing_nullable=True)
    op.alter_column('clients', 'jwt_private_key',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_comment='jwt private key with pem format',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'jwt_private_key',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_comment='jwt private key with pem format',
               existing_nullable=True)
    op.alter_column('clients', 'jwt_public_key',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_comment='jwt public key with pem format',
               existing_nullable=True)
    # ### end Alembic commands ###
